In [1]:
from datascience import *
import numpy as np

# NumPy Array examples

These are some of the things we can do in NumPy!

In [3]:
temperatures = make_array(3, 11, 7, 5, 6, 10, 12, 14, 15.6, 3.4, 2.1)
temperatures

array([ 3. , 11. ,  7. ,  5. ,  6. , 10. , 12. , 14. , 15.6,  3.4,  2.1])

see the help file for multiply - **element-wise** multiplication

In [6]:
np.multiply?

now, we will try to use this to convert these temps from C to F, which is temp in C * 9.0/5.0 + 32

In [4]:
np.multiply(temperatures, (9.0/5.0) + 32)

array([101.4 , 371.8 , 236.6 , 169.  , 202.8 , 338.  , 405.6 , 473.2 ,
       527.28, 114.92,  70.98])

what happened here? These numbers are not right.

It's a good idea to keep checking the order of operations (PEMDAS).

What we did above was take 9/5 plus 32 and then multiplied it.

We need to do multiplication first, then division, then addition.

The following resolves the MD first, then adds at the end (notice the addition on the outside of the function call.

In [5]:
np.multiply(temperatures, (9.0/5.0)) + 32

array([37.4 , 51.8 , 44.6 , 41.  , 42.8 , 50.  , 53.6 , 57.2 , 60.08,
       38.12, 35.78])

That's right!
It is, however, simpler to do this arithmetic directly on the array.
This will take each element in the array, multiply by 9/5 and add 32 in the correct order of operations.

In [6]:
temperatures * (9.0/5.0) + 32

array([37.4 , 51.8 , 44.6 , 41.  , 42.8 , 50.  , 53.6 , 57.2 , 60.08,
       38.12, 35.78])

# Some more NumPy Examples with Tables

Let's do the same thing with tables!
Let's load a table from a .csv file into python using Table().

In [7]:
cities = Table().read_table("cities.csv")
cities

Name                         | City         | State      | Temperature in C
Colebank, Jordan Elise       | San Franciso | California | 13
Collins, Matthew T           | Atlanta      | Georgia    | 9
Cook, Kylie Nichole          | Seattle      | Washington | 6
Downard, Andrew Nicholas     | nan          | nan        | 0
Duerinck, Randy Keith        | New York     | New York   | -10
Graham, Cassandra Michelle   | Cincinnati   | Ohio       | -12
Hodge, Devin Jonathan Monroe | Kansas City  | Missouri   | -4
Hoover, David R              | Sahuarita    | Arizona    | 19
Linden, Andrew Ryan          | Portland     | Oregon     | 6
Lynn, Matthew Michael        | Dallas       | Texas      | 10
... (3 rows omitted)

You can imagine converting the "Temperature in C" column into Fahrenheit (we alerady did that before)

In [8]:
cities.column("Temperature in C") * 9.0/5.0 + 32.0

array([55.4  , 48.2  , 42.8  , 32.   , 14.   , 10.4  , 24.8  , 66.2  ,
       42.8  , 50.   , 32.   , 57.218, 60.8  ])

Now, we can add a new column to the table by chaining some numpy methods.

We will use .with_column to add an "empty" new column to cities, and then populate it by creating a column that takes each element in "Temperature in C" and does the temp math on it.

These methods treat columns in a table as arrays.

In [14]:
cities.with_column("Temperature in F", cities.column("Temperature in C") * 9.0/5.0 + 32.0)

Name                         | City         | State      | Temperature in C | Temperature in F
Colebank, Jordan Elise       | San Franciso | California | 13               | 55.4
Collins, Matthew T           | Atlanta      | Georgia    | 9                | 48.2
Cook, Kylie Nichole          | Seattle      | Washington | 6                | 42.8
Downard, Andrew Nicholas     | nan          | nan        | 0                | 32
Duerinck, Randy Keith        | New York     | New York   | -10              | 14
Graham, Cassandra Michelle   | Cincinnati   | Ohio       | -12              | 10.4
Hodge, Devin Jonathan Monroe | Kansas City  | Missouri   | -4               | 24.8
Hoover, David R              | Sahuarita    | Arizona    | 19               | 66.2
Linden, Andrew Ryan          | Portland     | Oregon     | 6                | 42.8
Lynn, Matthew Michael        | Dallas       | Texas      | 10               | 50
... (3 rows omitted)

Here's an alternative method: We'll create a new array based by doing math on the "Temperatures in C" from the old table. 

In [11]:
F_column = cities.column("Temperature in C") * 9.0/5.0 + 32.0
F_column

array([55.4  , 48.2  , 42.8  , 32.   , 14.   , 10.4  , 24.8  , 66.2  ,
       42.8  , 50.   , 32.   , 57.218, 60.8  ])

and use the column stored in the new variable to attach to our old table.

In [12]:
cities.with_column("Temperature in F", F_column)

Name                         | City         | State      | Temperature in C | Temperature in F
Colebank, Jordan Elise       | San Franciso | California | 13               | 55.4
Collins, Matthew T           | Atlanta      | Georgia    | 9                | 48.2
Cook, Kylie Nichole          | Seattle      | Washington | 6                | 42.8
Downard, Andrew Nicholas     | nan          | nan        | 0                | 32
Duerinck, Randy Keith        | New York     | New York   | -10              | 14
Graham, Cassandra Michelle   | Cincinnati   | Ohio       | -12              | 10.4
Hodge, Devin Jonathan Monroe | Kansas City  | Missouri   | -4               | 24.8
Hoover, David R              | Sahuarita    | Arizona    | 19               | 66.2
Linden, Andrew Ryan          | Portland     | Oregon     | 6                | 42.8
Lynn, Matthew Michael        | Dallas       | Texas      | 10               | 50
... (3 rows omitted)

What was our old table's name?

In [13]:
cities

Name                         | City         | State      | Temperature in C
Colebank, Jordan Elise       | San Franciso | California | 13
Collins, Matthew T           | Atlanta      | Georgia    | 9
Cook, Kylie Nichole          | Seattle      | Washington | 6
Downard, Andrew Nicholas     | nan          | nan        | 0
Duerinck, Randy Keith        | New York     | New York   | -10
Graham, Cassandra Michelle   | Cincinnati   | Ohio       | -12
Hodge, Devin Jonathan Monroe | Kansas City  | Missouri   | -4
Hoover, David R              | Sahuarita    | Arizona    | 19
Linden, Andrew Ryan          | Portland     | Oregon     | 6
Lynn, Matthew Michael        | Dallas       | Texas      | 10
... (3 rows omitted)

Notice how even though we did all this stuff with numpy on our table, it didn't change. What do we do if we want to save our new table?

In [15]:
new_cities = cities.with_column("Temperature in F", F_column)
new_cities

Name                         | City         | State      | Temperature in C | Temperature in F
Colebank, Jordan Elise       | San Franciso | California | 13               | 55.4
Collins, Matthew T           | Atlanta      | Georgia    | 9                | 48.2
Cook, Kylie Nichole          | Seattle      | Washington | 6                | 42.8
Downard, Andrew Nicholas     | nan          | nan        | 0                | 32
Duerinck, Randy Keith        | New York     | New York   | -10              | 14
Graham, Cassandra Michelle   | Cincinnati   | Ohio       | -12              | 10.4
Hodge, Devin Jonathan Monroe | Kansas City  | Missouri   | -4               | 24.8
Hoover, David R              | Sahuarita    | Arizona    | 19               | 66.2
Linden, Andrew Ryan          | Portland     | Oregon     | 6                | 42.8
Lynn, Matthew Michael        | Dallas       | Texas      | 10               | 50
... (3 rows omitted)