In [2]:
# don't forget import statements:
from datascience import *
import numpy as np

In [3]:
# let's create an array


In [12]:
# let's create an array
make_array(100, 200, 300)

array([100, 200, 300])

In [13]:
make_array(1.0, 2.0, 3.0)

array([1., 2., 3.])

In [14]:
make_array("a", "b", "c")

array(['a', 'b', 'c'], dtype='<U1')

In [15]:
#let's retrieve something from the array using indexing
stooges = make_array("larry","moe","curly","shepp")
stooges[2]

'curly'

In [11]:
letters = make_array("a","b","c","d","e","f")
letters[1:4]

array(['b', 'c', 'd'], dtype='<U1')

In [16]:
# create a range using np.arange()
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [8]:
# create a range using np.arange()
range = np.arange(0,1000,10)
np.count_nonzero(range)
# how would you get this to return 100 items 
# (meaning include the 990 to 1000 interval)?


99